### ISSUE TITLE
Actual input not used in downstream request

### ISSUE THREAD

**Issue by miselico** [Semantic-Society/Recommender#5]
it appear that in this method: https://github.com/Semantic-Society/Recommender/blob/a654a01855cc9ccb1512641b5a2fd871cafbf774/src/main/java/de/rwth/dbis/neologism/recommender/bioportal/BioportalRecommeder.java#L127 
the input the user typed (query.queryString) is not included in the actual request, meaning one would always get the same results...

**Comment by JohannesLipp** [comment]
Does not apply anymore
